### ISSUE TITLE
Main tasks to prepare for publication

### ISSUE THREAD

**Issue by aboucaud** [LSSTDESC/madness#1]
**Meta list of tasks to be performed**

- [x] Add the docs (#6)
- [x] Rename maddeb to madness-deblender (Fixed by #8 )
- [x] Add clean notebooks (#6)
- [x] Add some tests !!!
- [x] #4
- [ ] Move repo to LSSTDESC GitHub repo ?!
- [x] Cleanup pyproject.toml
- [ ] #5
- [x] #3
- [x] [README] Rewrite introduction
- [x] [README] Add few code examples
- [x] [README] Add badges 😎️

**Tasks after publication**

- [x] Add a citation file CFF[^2]
- [ ] [README] Add citation

[^2]: see [docs about citation files](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files)
